grammar tables: emit good error when missing an operand type (#6145)
If a grammar change introduces a new optional operand kind,
then currently the error message is very unfriendly.  It's a Python
dictionary key error, with a call stack.

With this change, we get a single friendly error line like this,
but all on one line:

   error: unknown operand type SPV_OPERAND_TYPE_TENSOR_OPERANDS,
   from JSON grammar operand 'TensorOperands':
   consider updating spv_operand_type_t in spirv-tools/libspirv.h